mysite/models.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


class BaseModel(db.Model):
    __abstract__ = True
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.String(36), nullable=False, index=True)


class First(BaseModel):
    __table_name__ = 'first'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.String(36))
    creator = db.Column(db.String, nullable=False, unique=True)
    firm_name = db.Column(db.String)
    number = db.Column(db.Integer)


class Second(BaseModel):
    __table_name__ = 'second'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.String(36))
    name = db.Column(db.String)
    days = db.Column(db.Integer)
    personal = db.Column(db.String)


class Third(BaseModel):
    __table_name__ = 'third'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.String(36))
    week = db.Column(db.String)

mysite/__init__.py
from .app import run_app

mysite/app.py
from flask import Flask

from .config import DefaultConfig
from .models import db
from .routes import admin


def create_app(config) -> Flask:
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(config)
    app.secret_key = config.KEY
    app.register_blueprint(admin)
    app.config['SQLALCHEMY_DATABASE_URI'] = config.DATA_BASE
    db.init_app(app)
    return app


def run_app() -> any:
    app = create_app(DefaultConfig)
    # create_database_structure(app)
    return app.run()

mysite/routes.py
import os
import uuid

import pandas as pd
from flask import Blueprint, render_template, request, session

from .models import First, Second, Third, db
from .processor import data_readable, process_data, search_folder, send_email

admin = Blueprint('admin', __name__)


@admin.route('/', methods=['GET'])
def main_page() -> str:
    """
    Renders the main page of the application.
    If the user does not have a 'user_id' in the session, it assigns one.

    Returns:
        str: The rendered HTML template for the main page.
    """
    if 'user_id' not in session:
        session['user_id'] = str(uuid.uuid4())
        session['is_complete'] = False
    return render_template('main_page.html')


@admin.route('/first_step', methods=['GET'])
def first_step() -> str:
    """
    Renders the first step page of the application.
    If the user does not have a 'user_id' in the session, it assigns one.

    Returns:
        str: The rendered HTML template for the first step.
    """
    if 'user_id' not in session:
        session['user_id'] = str(uuid.uuid4())
        session['is_complete'] = False
    return render_template('first_step.html')


@admin.route('/second_step', methods=['GET', 'POST'])
def second_step() -> str:
    """
    Handles the second step of the process, where user information (creator, firm name, number) is collected.
    On POST request, it saves the data to the database.

    Returns:
        str: The rendered HTML template for the second step.
    """
    if request.method == 'POST':
        name = request.form.get('creator')
        firm_name = request.form.get('firm_name')
        number = request.form.get('number')
        user_id = session.get('user_id')
        if not user_id:
            return render_template('main_page.html')

        new_entry = First(
            creator=name,
            firm_name=firm_name,
            number=number,
            user_id=user_id
        )
        db.session.add(new_entry)
        db.session.commit()

        return render_template(
            'second_step.html',
            number=int(number)
        )

    number = request.args.get('number')
    return render_template(
        'second_step.html',
        number=int(number)
    )


@admin.route('/third_step', methods=['GET', 'POST'])
def third_step() -> str:
    """
    Handles the third step where a list of names, days, and personal days is collected.
    On POST request, it saves the data to the database.

    Returns:
        str: The rendered HTML template for the third step.
    """
    if request.method == 'POST':
        names = request.form.getlist('names[]')
        days = request.form.getlist('days[]')
        personal = request.form.getlist('personal[]')
        user_id = session.get('user_id')
        if not user_id:
            return render_template('main_page.html')

        for name, day, personal in zip(names, days, personal):
            new_entry = Second(
                name=name,
                days=day,
                personal=personal,
                user_id=user_id
            )
            db.session.add(new_entry)
            db.session.commit()

        return render_template('third_step.html')

    return render_template('third_step.html')


@admin.route('/fourth_step', methods=['GET', 'POST'])
def fourth_step() -> str:
    """
    Handles the fourth step where the weekly schedule is saved, and the schedule is processed.
    On POST request, the schedule is generated and displayed as an HTML table.

    Returns:
        str: The rendered HTML template for the fourth step with the schedule table.
    """
    if request.method == 'POST':
        monday = request.form.get('monday')
        tuesday = request.form.get('tuesday')
        wednesday = request.form.get('wednesday')
        thursday = request.form.get('thursday')
        friday = request.form.get('friday')
        saturday = request.form.get('saturday')
        sunday = request.form.get('sunday')
        user_id = session.get('user_id')
        if not user_id:
            return render_template('main_page.html')

        new_list = [
            monday,
            tuesday,
            wednesday,
            thursday,
            friday,
            saturday,
            sunday
        ]
        new_entry = Third(
            week=(str(new_list)), user_id=user_id
        )
        db.session.add(new_entry)
        db.session.commit()

        first_data = First.query.filter_by(user_id=user_id).all()
        second_data = Second.query.filter_by(user_id=user_id).all()
        third_data = Third.query.filter_by(user_id=user_id).all()

        data = data_readable([first_data, second_data, third_data])
        process_data(data, user_id)
        df = pd.read_csv(search_folder(user_id, 'csv'))

        table_html = df.to_html(classes='table table-striped table-bordered')

        return render_template(
            'fourth_step.html',
            table_html=table_html
        )

    return render_template('fourth_step.html')


@admin.route('/fifth_step', methods=['POST'])
def fifth_step() -> str:
    """
    Handles the fifth step where the user can enter an email and request to send the generated schedule file.
    On POST request, the email is sent with the file as an attachment.

    Returns:
        str: The rendered HTML template for the fifth step.
    """
    user_id = session.get('user_id')
    email = request.form.get('email')
    file_type = request.form.get('fileType')
    send_file_button = request.form.get('send_file')

    if not user_id:
        return render_template('main_page.html')

    if send_file_button:
        send_email(email, search_folder(user_id, file_type))
        return render_template('main_page.html')

    return render_template(
        'fifth_step.html',
        data=[email, file_type]
    )


@admin.route('/cleanup_session', methods=['POST'])
def cleanup_session() -> str:
    """
    Cleans up the session by deleting the user's data from the database and removing any associated files.

    Returns:
        str: An empty string with a status code of 204 (No Content) if successful.
        If an error occurs, it returns a 500 status code with an error message.
    """
    user_id = session.get('user_id')
    if not user_id:
        return '', 204

    try:
        db.session.query(First).filter_by(user_id=user_id).delete()
        db.session.query(Second).filter_by(user_id=user_id).delete()
        db.session.query(Third).filter_by(user_id=user_id).delete()
        db.session.commit()

        file_paths = [
            os.path.join('schedule', f'{user_id}.csv'),
            os.path.join('schedule', f'{user_id}.xlsx')
        ]
        for file_path in file_paths:
            if os.path.exists(file_path):
                os.remove(file_path)

        session.pop('user_id', None)

        return '', 204
    except Exception as e:
        db.session.rollback()
        print(f"Error clean data: {e}")
        return '', 500

mysite/templates/fifth_step.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Schedule first</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <script src="{{ url_for('static', filename='dist/bundle.js') }}"></script>

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
        <img src="{{ url_for('static', filename='app_photo/logo/schedule_logo.png') }}" alt="Logo" width="30" height="30" class="d-inline-block align-text-top">
        </a>
        <span class="navbar-text me-3" style="color: black">Step </span>
        <span class="navbar-text me-3" style="color: black">Final</span>
        <span class="navbar-text me-3" id="current-time" style="color: black">Time</span>
    </div>
</nav>

<div class="container">
    <div class="main-block">
        <main class="form-signin">
            <form class="text-center" action="/fifth_step" method="POST">
                <div class="form-floating mb-3">
                    <h4 class="h4 mb-4 fw-normal"
                        style="color: #FF4800; font-size: 4em; line-height: 2;">
                        Thanks for using Schedule creator
                    </h4>

                    <h5 class="h3 mb-3 fw-normal"
                        style="color: white; font-size: 1.2em; line-height: 1.8;">
                        Before sending your schedule, please check that the email and file format you entered are correct.
                    </h5>

                    <h6>
                        <span class="label" style="font-weight: bold; color: #FF4800; font-size: 1.1em;">Your email:</span>
                        <input type="hidden" name="email" value="{{ data[0] }}">
                        <span class="value" style="color: white; font-size: 1.1em;">{{ data[0] }}</span>
                    </h6>

                    <h6>
                        <span class="label" style="font-weight: bold; color: #FF4800; font-size: 1.1em;">Your file type:</span>
                        <input type="hidden" name="fileType" value="{{ data[1] }}">
                        <span class="value" style="color: white; font-size: 1.1em;">{{ data[1] }}</span>
                    </h6>

                    <button class="btn btn-primary py-2 w-100" type="submit"
                            style="max-width: 400px; background-color: #FF4800; border-color: #FF4800;"
                            name="send_file" value="true">
                        Send my file
                    </button>
                </div>
            </form>
        </main>
    </div>
</div>



<script type="module">
    import { setupNavigation } from '../static/js/navigationhandler.js';

    setupNavigation();
</script>

<script src="{{ url_for('static', filename='js/time.js') }}"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

mysite/templates/first_step.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Schedule first</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <script src="{{ url_for('static', filename='dist/bundle.js') }}"></script>

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
        <img src="{{ url_for('static', filename='app_photo/logo/schedule_logo.png') }}" alt="Logo" width="30" height="30" class="d-inline-block align-text-top">
        </a>
        <span class="navbar-text me-3" style="color: black">Step </span>
        <span class="navbar-text me-3" style="color: black">1 / 4</span>
        <span class="navbar-text me-3" id="current-time" style="color: black">Time</span>
    </div>
</nav>

<div class="container">
    <div class="main-block">
        <main class="form-signin">
            <form class="text-center" action="{{ url_for('admin.second_step') }}" method="POST">
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" id="creator" name="creator" placeholder="Enter your name" required>
                    <label for="creator">Enter your name</label>
                </div>
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" id="firm_name" name="firm_name" placeholder="Enter firm name" required>
                    <label for="firm_name">Enter firm name</label>
                </div>
                <div class="form-floating mb-3" style="max-width: 400px; margin: 0 auto;" >
                    <select class="form-control" id="intInput" name='number' required>
                        <option value="" disabled selected>🦊</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                    </select>
                    <label for="intInput" style="line-height: 1.5;">Number of employees</label>
                </div>

                <div class="mt-auto">
                    <button class="btn btn-primary py-2 w-100" type="submit" style="max-width: 400px; background-color: #FF4800; border-color: #FF4800;">Next step 2/4</button>
                </div>
            </form>
        </main>
    </div>
</div>

<script type="module">
    import { setupNavigation } from '../static/js/navigationhandler.js';

    setupNavigation();
</script>

<script src="{{ url_for('static', filename='js/time.js') }}"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

mysite/templates/fourth_step.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Schedule first</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <script src="{{ url_for('static', filename='dist/bundle.js') }}"></script>

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
        <img src="{{ url_for('static', filename='app_photo/logo/schedule_logo.png') }}" alt="Logo" width="30" height="30" class="d-inline-block align-text-top">
        </a>
        <span class="navbar-text me-3" style="color: black">Step </span>
        <span class="navbar-text me-3" style="color: black">4 / 4</span>
        <span class="navbar-text me-3" id="current-time" style="color: black">Time</span>
    </div>
</nav>

<div class="container mt-3">
    <h1>Your Schedule</h1>
    <div class="table-responsive">
        {{ table_html|safe }}
    </div>
    <h4>Instruction</h4>
    <h6>Nan - free day</h6>
    <h6>X - work day</h6>
    <h6>? - day without worker</h6>

    <div class="form-floating mb-8">
        <select class="form-select" id="fileType" name="fileType" required>
            <option value="csv">csv</option>
            <option value="xlsx">xlsx</option>
        </select>
        <label for="fileType">Choose file type</label>
    </div>

    <form method="POST" action="/fifth_step" style="margin-top: 20px;">
        <div class="form-floating mb-3">
            <div style="display: flex; align-items: center;">
                <input type="text" class="form-control" id="username" name="username" placeholder="Enter your email" required style="flex: 1;" />
                <span style="margin: 0 5px;">@</span>
                <select id="domain" class="form-select" style="width: auto;">
                    <option value="gmail.com">gmail.com</option>
                    <option value="yandex.ru">yandex.ru</option>
                </select>
            </div>
        </div>
        <input type="hidden" id="email" name="email">
        <button class="btn btn-primary py-2 w-100" type="submit" style="max-width: 400px; background-color: #FF4800; border-color: #FF4800;">
            Final step
        </button>
    </form>
</div>


<script type="module">
    import { setupEmail } from '../static/js/email.js';

    setupEmail();
</script>

<script type="module">
    import { setupNavigation } from '../static/js/navigationhandler.js';

    setupNavigation();
</script>

<script src="{{ url_for('static', filename='js/time.js') }}"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

mysite/templates/main_page.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Schedule app</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="d-flex justify-content-center align-items-center min-vh-100">
  <main class="form-signin" style="max-width: 1000px;">
    <form class="text-center" action="/first_step">
        <h1 class="h3 mb-3 fw-normal" style="color: #FF4800; font-size: 4em;line-height: 2;">Welcome to Schedule Creator</h1>
        <h4 class="h3 mb-3 fw-normal" style="color: #FF4800; line-height: 2;">You need 4 steps to make the perfect schedule</h4>
        <h5 class="h3 mb-3 fw-normal" style="color: #FF4800; line-height: 2;">Below are a few rules of use</h5>

        <h6 class="h3 mb-3 fw-normal" style="color: #white; line-height: 2; font-size: 1em;">
            1) Any closing of the page will result in the deletion of your data
        </h6>
        <h6 class="h3 mb-3 fw-normal" style="color: #white; line-height: 2; font-size: 1em;">
            2) The schedule is created always for the next month
        </h6>
        <h6 class="h3 mb-3 fw-normal" style="color: #white; line-height: 2; font-size: 1em;">
            3) The graph creator is powered by your data and will adapt to your input data
        </h6>



        <button class="btn btn-primary py-2 w-100" type="submit" style="max-width: 400px; background-color: #FF4800; border-color: #FF4800; margin-top: 40px;">
            Lets start
        </button>
    </form>
  </main>
</div>

<script type="module">
    import { Clean } from '../static/js/main.js';

    Clean();
</script>

</body>
</html>

mysite/templates/second_step.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Schedule first</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <script src="{{ url_for('static', filename='dist/bundle.js') }}"></script>

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
        <img src="{{ url_for('static', filename='app_photo/logo/schedule_logo.png') }}" alt="Logo" width="30" height="30" class="d-inline-block align-text-top">
        </a>
        <span class="navbar-text me-3" style="color: black">Step </span>
        <span class="navbar-text me-3" style="color: black">2 / 4</span>
        <span class="navbar-text me-3" id="current-time" style="color: black">Time</span>
    </div>
</nav>

<div class="container">
    <div class="main-block">
        <main class="form-signin">
            <form action="{{ url_for('admin.third_step') }}" method="POST">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Name of works</th>
                            <th>Number of days off</th>
                            <th>Private days off</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in range(number) %}
                        <tr>
                            <td><input type="text" name="names[]" placeholder="Stefan" class="form-control" required pattern="[A-Za-zА-Яа-яЁё]+" title="Contain only letters"></td>
                            <td><input type="text" name="days[]" placeholder="6" class="form-control" required pattern="\d+" title="Write one number"></td>
                            <td><input type="text" name="personal[]" placeholder="1,23,28" class="form-control" required pattern="(\d+)(,\d+)*" title="Numbers separated by commas"></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="mt-auto">
                    <button class="btn btn-primary py-2 w-100" type="submit" style="max-width: 400px; background-color: #FF4800; border-color: #FF4800;">Next step 3/4</button>
                </div>
            </form>
        </main>
    </div>
</div>

<script type="module">
    import { setupNavigation } from '../static/js/navigationhandler.js';

    setupNavigation();
</script>

<script src="{{ url_for('static', filename='js/time.js') }}"></script>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

mysite/templates/third_step.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Schedule first</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <script src="{{ url_for('static', filename='dist/bundle.js') }}"></script>

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
        <img src="{{ url_for('static', filename='app_photo/logo/schedule_logo.png') }}" alt="Logo" width="30" height="30" class="d-inline-block align-text-top">
        </a>
        <span class="navbar-text me-3" style="color: black">Step </span>
        <span class="navbar-text me-3" style="color: black">3 / 4</span>
        <span class="navbar-text me-3" id="current-time" style="color: black">Time</span>
    </div>
</nav>

<div class="container">
    <div class="main-block">
        <main class="form-signin">
            <form class="text-center" action="{{ url_for('admin.fourth_step') }}" method="POST">
                <div class="form-floating mb-3">
                    <input type="number" class="form-control" id="monday" name="monday" placeholder="Monday" required min="0">
                    <label for="monday">Monday</label>
                </div>
                <div class="form-floating mb-3">
                    <input type="number" class="form-control" id="tuesday" name="tuesday" placeholder="Tuesday" required min="0">
                    <label for="tuesday">Tuesday</label>
                </div>
                <div class="form-floating mb-3">
                    <input type="number" class="form-control" id="wednesday" name="wednesday" placeholder="Wednesday" required min="0">
                    <label for="wednesday">Wednesday</label>
                </div>
                <div class="form-floating mb-3">
                    <input type="number" class="form-control" id="thursday" name="thursday" placeholder="Thursday" required min="0">
                    <label for="thursday">Thursday</label>
                </div>
                <div class="form-floating mb-3">
                    <input type="number" class="form-control" id="friday" name="friday" placeholder="Friday" required min="0">
                    <label for="friday">Friday</label>
                </div>
                <div class="form-floating mb-3">
                    <input type="number" class="form-control" id="saturday" name="saturday" placeholder="Saturday" required min="0">
                    <label for="saturday">Saturday</label>
                </div>
                <div class="form-floating mb-3">
                    <input type="number" class="form-control" id="sunday" name="sunday" placeholder="Sunday" required min="0">
                    <label for="sunday">Sunday</label>
                </div>

                <div class="mt-auto">
                    <button class="btn btn-primary py-2 w-100" type="submit" style="max-width: 400px; background-color: #FF4800; border-color: #FF4800;">
                        Next step 4/4
                    </button>
                </div>
            </form>
        </main>
    </div>
</div>

<script type="module">
    import { setupNavigation } from '../static/js/navigationhandler.js';

    setupNavigation();
</script>

<script src="{{ url_for('static', filename='js/time.js') }}"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>